changelog:
    categories:
        - title: Breaking Changes
          labels:
              - breaking-change
        - title: Added
          labels:
              - feature
        - title: Changed
          labels:
              - refactor
              - performance
        - title: Deprecated
          labels:
              - deprecated
        - title: Removed
          labels:
              - removed
        - title: Fixed
          labels:
              - bugfix
              - test
        - title: Security
          labels:
              - security
        - title: Other Changes
          labels:
              - build
              - chore
              - ci
              - docs
              - style
