#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

if [ "$DASHBRD_ENABLE_PREPUSH_LINTER" = "true" ]; then
    npx eslint --no-error-on-unmatched-pattern $(git diff --name-only --diff-filter=ACMRTUXB origin/$(git rev-parse --abbrev-ref HEAD) $(git rev-parse --abbrev-ref HEAD) | grep -E "resources/**/*.(tsx|ts|jsx|js)")
else
  echo "DASHBRD_ENABLE_PREPUSH_LINTER is not enabled. Skipping linting."
fi
